# Generated by Django 4.2.29 on 2026-04-05 18:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApifyApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=100)),
                ('api_key', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_exhausted', models.BooleanField(default=False)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApolloApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=100)),
                ('api_key', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_exhausted', models.BooleanField(default=False)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name_latest', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(max_length=255, unique=True)),
                ('active_domain', models.CharField(blank=True, default='', max_length=255)),
                ('domain_status', models.CharField(choices=[('unknown', 'Unknown'), ('set', 'Set'), ('doubt', 'Doubt')], default='unknown', max_length=20)),
                ('pattern_status', models.CharField(choices=[('unknown', 'Unknown'), ('set', 'Set'), ('doubt', 'Doubt')], default='unknown', max_length=20)),
                ('daily_send_limit', models.PositiveIntegerField(default=10)),
                ('rolling_7d_send_limit', models.PositiveIntegerField(default=25)),
                ('is_blocked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['normalized_name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyRecruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255)),
                ('normalized_person_name', models.CharField(db_index=True, max_length=255)),
                ('email', models.CharField(default='none', max_length=320)),
                ('email_source', models.CharField(choices=[('json_upload', 'JSON Upload'), ('apollo_verified', 'Apollo Verified'), ('apollo_other', 'Apollo Other'), ('guessed_pattern', 'Guessed Pattern'), ('manual_edit', 'Manual Edit')], default='json_upload', max_length=30)),
                ('email_status', models.CharField(choices=[('none', 'None'), ('apollo_verified', 'Apollo Verified'), ('apollo_nonverified', 'Apollo Nonverified'), ('guessed_unverified', 'Guessed Unverified'), ('verifier_deliverable', 'Verifier Deliverable'), ('verifier_failed', 'Verifier Failed'), ('manual_override', 'Manual Override')], db_index=True, default='none', max_length=30)),
                ('is_master_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiters', to='core.company')),
            ],
            options={
                'ordering': ['company__normalized_name', 'normalized_person_name'],
            },
        ),
        migrations.CreateModel(
            name='DailyBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_date', models.DateField(unique=True)),
                ('lookback_hours', models.PositiveIntegerField(default=24)),
                ('max_jobs_requested', models.PositiveIntegerField(default=2)),
                ('apify_run_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('import_started_at', models.DateTimeField(blank=True, null=True)),
                ('import_finished_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-batch_date'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerifierApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=100)),
                ('api_key', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_exhausted', models.BooleanField(default=False)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_job_id', models.CharField(blank=True, default='', max_length=255)),
                ('linkedin_url', models.URLField(max_length=1000)),
                ('apply_url', models.URLField(blank=True, default='', max_length=1000)),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=500)),
                ('salary', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField()),
                ('company_linkedin', models.URLField(blank=True, default='', max_length=1000)),
                ('recruiter_name', models.CharField(blank=True, default='', max_length=255)),
                ('recruiter_title', models.CharField(blank=True, default='', max_length=255)),
                ('recruiter_linkedin', models.URLField(blank=True, default='', max_length=1000)),
                ('ai_hiring_mgr_name', models.CharField(blank=True, default='', max_length=255)),
                ('ai_hiring_mgr_email', models.CharField(blank=True, default='', max_length=320)),
                ('normalized_company', models.CharField(db_index=True, max_length=255)),
                ('normalized_title', models.CharField(db_index=True, max_length=500)),
                ('normalized_location', models.CharField(db_index=True, max_length=500)),
                ('dedupe_key', models.CharField(db_index=True, max_length=1500)),
                ('sort_company', models.CharField(db_index=True, max_length=255)),
                ('sort_title', models.CharField(db_index=True, max_length=500)),
                ('sort_location', models.CharField(db_index=True, max_length=500)),
                ('prior_7d_company_roles', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('imported', 'Imported'), ('recruiters_pending', 'Recruiters Pending'), ('email_discovery_ready', 'Email Discovery Ready'), ('email_discovery_done', 'Email Discovery Done'), ('email_generated', 'Email Generated'), ('approved', 'Approved'), ('test_sent', 'Test Sent'), ('real_sent', 'Real Sent'), ('failed', 'Failed'), ('blocked', 'Blocked')], db_index=True, default='imported', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.company')),
                ('daily_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.dailybatch')),
            ],
            options={
                'ordering': ['sort_company', 'sort_title', 'sort_location', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobRecruiterTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email_snapshot', models.CharField(default='none', max_length=320)),
                ('recipient_name_snapshot', models.CharField(max_length=255)),
                ('selection_order', models.PositiveIntegerField(default=0)),
                ('is_selected_for_job', models.BooleanField(default=False)),
                ('is_verified_for_job', models.BooleanField(default=False)),
                ('is_test_target_used', models.BooleanField(default=False)),
                ('is_sent_real', models.BooleanField(default=False)),
                ('send_block_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_targets', to='core.companyrecruiter')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='core.jobposting')),
            ],
            options={
                'ordering': ['job_posting', 'selection_order', 'recipient_name_snapshot'],
            },
        ),
        migrations.CreateModel(
            name='RecruiterJsonUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('raw_json_text', models.TextField()),
                ('normalized_company_count', models.PositiveIntegerField(default=0)),
                ('total_people_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SenderAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('app_password', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_paused', models.BooleanField(default=False)),
                ('daily_limit', models.PositiveIntegerField(default=50)),
                ('sent_today_count', models.PositiveIntegerField(default=0)),
                ('round_robin_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['round_robin_order', 'email'],
            },
        ),
        migrations.CreateModel(
            name='SendRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(choices=[('test', 'Test'), ('real', 'Real')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_manually', models.BooleanField(default=False)),
                ('delay_seconds', models.PositiveIntegerField(default=15)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TestEmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rotation_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['rotation_order', 'email'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('imported', 'Imported'), ('filtered_apply', 'Filtered Apply'), ('filtered_reject', 'Filtered Reject'), ('deduped', 'Deduped'), ('recruiter_json_uploaded', 'Recruiter JSON Uploaded'), ('apollo_done', 'Apollo Done'), ('verifier_done', 'Verifier Done'), ('email_generated', 'Email Generated'), ('approved', 'Approved'), ('test_sent', 'Test Sent'), ('real_sent', 'Real Sent'), ('failed', 'Failed')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_posting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to='core.jobposting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SentEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('subject_snapshot', models.CharField(max_length=500)),
                ('body_snapshot', models.TextField()),
                ('attachment_path', models.CharField(blank=True, default='', max_length=1000)),
                ('send_type', models.CharField(choices=[('test', 'Test'), ('real', 'Real')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_logs', to='core.jobposting')),
                ('job_recruiter_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_logs', to='core.jobrecruitertarget')),
                ('send_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_logs', to='core.sendrun')),
                ('sender_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_logs', to='core.senderaccount')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SenderDailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField(default=django.utils.timezone.localdate)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('sender_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usages', to='core.senderaccount')),
            ],
            options={
                'ordering': ['-usage_date', 'sender_account__email'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('body', models.TextField(blank=True, default='')),
                ('generation_status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=100)),
                ('edited_manually', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_posting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_email', to='core.jobposting')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_posting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_record', to='core.jobposting')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sentemaillog',
            constraint=models.UniqueConstraint(condition=models.Q(('send_type', 'real'), ('status', 'sent')), fields=('to_email',), name='uniq_real_sent_email_once'),
        ),
        migrations.AddConstraint(
            model_name='senderdailyusage',
            constraint=models.UniqueConstraint(fields=('sender_account', 'usage_date'), name='uniq_sender_usage_per_day'),
        ),
        migrations.AddConstraint(
            model_name='jobrecruitertarget',
            constraint=models.UniqueConstraint(fields=('job_posting', 'company_recruiter'), name='uniq_job_company_recruiter_target'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['daily_batch', 'status'], name='core_jobpos_daily_b_43545f_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['normalized_company', 'normalized_title', 'normalized_location'], name='core_jobpos_normali_eb8f7d_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyrecruiter',
            constraint=models.UniqueConstraint(fields=('company', 'normalized_person_name'), name='uniq_company_normalized_person'),
        ),
    ]
