# Generated by Django 5.2.12 on 2026-04-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='canonical_company',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='canonical_location',
            field=models.CharField(blank=True, db_index=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='canonical_title',
            field=models.CharField(blank=True, db_index=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='description_fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='linkedin_geo_region_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='linkedin_people_search_urls',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='normalized_apply_url',
            field=models.URLField(blank=True, db_index=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='normalized_linkedin_url',
            field=models.URLField(blank=True, db_index=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='prior_7d_company_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['canonical_company', 'canonical_title', 'canonical_location'], name='core_jobpos_canonic_9c2869_idx'),
        ),
    ]
