# Generated by Django 5.2.12 on 2026-04-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jobposting_canonical_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='direct_recruiter_email',
            field=models.CharField(blank=True, default='', max_length=320),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='direct_recruiter_email_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='direct_recruiter_email_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
