# Generated by Django 5.2.12 on 2026-04-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_jobposting_direct_recruiter_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='apify_linkedin_org_url',
            field=models.URLField(blank=True, db_index=True, default='', max_length=1000),
        ),
    ]
