# Generated by Django 5.2.12 on 2026-04-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_jobposting_apify_linkedin_org_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentemaillog",
            name="message_type",
            field=models.CharField(
                choices=[("initial", "Initial"), ("follow_up", "Follow Up")],
                db_index=True,
                default="initial",
                max_length=20,
            ),
        ),
    ]

