# Generated by Django 5.2.12 on 2026-04-19 00:00

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_sentemaillog_message_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sentemaillog",
            name="uniq_real_sent_email_once",
        ),
        migrations.AddConstraint(
            model_name="sentemaillog",
            constraint=models.UniqueConstraint(
                fields=("to_email",),
                condition=Q(send_type="real", status="sent", message_type="initial"),
                name="uniq_real_sent_initial_once",
            ),
        ),
    ]

