# Generated by Django 5.2.12 on 2026-04-19 00:00

from django.db import migrations, models
from django.db.models import Max


def backfill_email_sent(apps, schema_editor):
    CompanyRecruiter = apps.get_model("core", "CompanyRecruiter")
    SentEmailLog = apps.get_model("core", "SentEmailLog")

    rows = (
        SentEmailLog.objects
        .filter(send_type="real", status="sent", message_type="initial")
        .values("to_email")
        .annotate(last_sent_at=Max("sent_at"))
    )

    for row in rows:
        email = (row.get("to_email") or "").strip().lower()
        sent_at = row.get("last_sent_at")
        if not email or email == "none" or not sent_at:
            continue

        CompanyRecruiter.objects.filter(email=email).update(
            email_sent=True,
            email_sent_date=sent_at.date(),
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_sentemaillog_unique_initial_only"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ApifyApiKey",
        ),
        migrations.DeleteModel(
            name="ApolloApiKey",
        ),
        migrations.DeleteModel(
            name="EmailVerifierApiKey",
        ),
        migrations.RemoveField(
            model_name="companyrecruiter",
            name="email_source",
        ),
        migrations.RemoveField(
            model_name="companyrecruiter",
            name="email_status",
        ),
        migrations.RemoveField(
            model_name="companyrecruiter",
            name="is_master_verified",
        ),
        migrations.RemoveField(
            model_name="companyrecruiter",
            name="last_verified_at",
        ),
        migrations.RemoveField(
            model_name="companyrecruiter",
            name="notes",
        ),
        migrations.AddField(
            model_name="companyrecruiter",
            name="email_sent",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="companyrecruiter",
            name="email_sent_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(
            code=backfill_email_sent,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="jobposting",
            name="direct_recruiter_email",
        ),
        migrations.RemoveField(
            model_name="jobposting",
            name="direct_recruiter_email_source",
        ),
        migrations.RemoveField(
            model_name="jobposting",
            name="direct_recruiter_email_status",
        ),
    ]
