# Generated by ChatGPT on 2026-04-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_simplify_recruiters_and_remove_keys"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("cold_email", "Cold Email"),
                            ("company_normalization", "Company Normalization"),
                            ("job_filter", "Job Filter"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["purpose", "-is_active", "name", "-updated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="prompttemplate",
            constraint=models.UniqueConstraint(fields=("purpose", "name"), name="uniq_prompt_purpose_name"),
        ),
    ]

