# Generated by Django 4.2.30 on 2026-04-21 12:43

from django.db import migrations, models, transaction
import django.db.models.functions.text


def _norm(email: str) -> str:
    return (email or "").strip().lower()


def dedupe_and_normalize_emails(apps, schema_editor):
    SenderAccount = apps.get_model("core", "SenderAccount")
    SenderDailyUsage = apps.get_model("core", "SenderDailyUsage")
    SentEmailLog = apps.get_model("core", "SentEmailLog")
    TestEmailAccount = apps.get_model("core", "TestEmailAccount")

    with transaction.atomic():
        sender_rows = list(SenderAccount.objects.order_by("id").values_list("id", "email"))
        sender_groups = {}
        for sender_id, email in sender_rows:
            sender_groups.setdefault(_norm(email), []).append((sender_id, email))

        for norm_email, items in sender_groups.items():
            keep_id, keep_email = items[0]
            dup_ids = [sid for sid, _ in items[1:]]
            if dup_ids:
                SenderDailyUsage.objects.filter(sender_account_id__in=dup_ids).update(sender_account_id=keep_id)
                SentEmailLog.objects.filter(sender_account_id__in=dup_ids).update(sender_account_id=keep_id)
                SenderAccount.objects.filter(id__in=dup_ids).delete()
            if keep_email != norm_email:
                SenderAccount.objects.filter(id=keep_id).update(email=norm_email)

        test_rows = list(TestEmailAccount.objects.order_by("id").values_list("id", "email"))
        test_groups = {}
        for test_id, email in test_rows:
            test_groups.setdefault(_norm(email), []).append((test_id, email))

        for norm_email, items in test_groups.items():
            keep_id, keep_email = items[0]
            dup_ids = [tid for tid, _ in items[1:]]
            if dup_ids:
                TestEmailAccount.objects.filter(id__in=dup_ids).delete()
            if keep_email != norm_email:
                TestEmailAccount.objects.filter(id=keep_id).update(email=norm_email)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_prompttemplate'),
    ]

    operations = [
        migrations.RunPython(dedupe_and_normalize_emails, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='senderaccount',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='uniq_sender_email_ci', violation_error_message='Sender account with this email already exists.'),
        ),
        migrations.AddConstraint(
            model_name='testemailaccount',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='uniq_test_email_ci', violation_error_message='Test email account with this email already exists.'),
        ),
    ]
