# Generated by Django 4.2.30 on 2026-04-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_senderaccount_uniq_sender_email_ci_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApifyApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=100, unique=True)),
                ('api_key', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_exhausted', models.BooleanField(default=False)),
                ('rotation_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rotation_order', 'key_name'],
            },
        ),
    ]
