# Generated by Django 4.2.30 on 2026-05-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_sender_cooldown_suppression_and_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsetting',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
