# Generated by Django 4.2.30 on 2026-05-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_appsetting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsetting',
            name='max_people_per_company',
            field=models.PositiveIntegerField(default=10, help_text='Global cap: max recruiters fetched and emails sent per company.'),
        ),
    ]
