# Generated by Django 4.2.30 on 2026-05-15 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_jobposting_is_manual_email_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetedPeopleLookupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_names', models.TextField(blank=True, default='')),
                ('parsed_names', models.JSONField(blank=True, default=list)),
                ('allow_regular_fallback', models.BooleanField(default=True)),
                ('fallback_blocked_by_credit_guard', models.BooleanField(default=False)),
                ('max_people', models.PositiveIntegerField(default=10)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='running', max_length=20)),
                ('emails_found', models.PositiveIntegerField(default=0)),
                ('credits_consumed', models.PositiveIntegerField(default=0)),
                ('credits_not_converted_to_email', models.PositiveIntegerField(default=0)),
                ('source_counts', models.JSONField(blank=True, default=dict)),
                ('result_rows', models.JSONField(blank=True, default=list)),
                ('totals', models.JSONField(blank=True, default=dict)),
                ('run_log_path', models.CharField(blank=True, default='', max_length=1000)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_people_lookup_runs', to='core.company')),
                ('job_posting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_people_lookup_runs', to='core.jobposting')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
