# Generated by Django 4.2.30 on 2026-05-16 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_targeted_people_lookup_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_key', models.CharField(max_length=500)),
                ('from_header', models.CharField(blank=True, default='', max_length=1000)),
                ('subject', models.CharField(blank=True, default='', max_length=1000)),
                ('message_date', models.DateTimeField(blank=True, null=True)),
                ('classification', models.CharField(choices=[('reply', 'Reply'), ('bounce', 'Hard Bounce'), ('blocked', 'Block Warning'), ('notice', 'Notice')], db_index=True, max_length=30)),
                ('detected_email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('snippet', models.TextField(blank=True, default='')),
                ('raw_detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_sent_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_events', to='core.sentemaillog')),
                ('sender_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_scan_events', to='core.senderaccount')),
            ],
            options={
                'ordering': ['-message_date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='inboxscanevent',
            constraint=models.UniqueConstraint(fields=('sender_account', 'message_key'), name='uniq_inbox_event_per_sender_msg'),
        ),
    ]
