# Generated by Django 4.2.30 on 2026-06-02 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_apollo_verified_email_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApolloRejectedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.CharField(db_index=True, max_length=320)),
                ('email_status', models.CharField(blank=True, db_index=True, default='unknown', max_length=30)),
                ('apollo_person_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('reason', models.CharField(blank=True, default='', max_length=120)),
                ('source_workflow', models.CharField(blank=True, default='', max_length=80)),
                ('run_log_path', models.CharField(blank=True, default='', max_length=1000)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apollo_rejected_emails', to='core.company')),
                ('job_posting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apollo_rejected_emails', to='core.jobposting')),
                ('targeted_lookup_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apollo_rejected_emails', to='core.targetedpeoplelookuprun')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['company', 'email_status'], name='core_apollo_company_c88e5a_idx'), models.Index(fields=['email', 'email_status'], name='core_apollo_email_c0698f_idx')],
            },
        ),
    ]
