# Generated by Django 4.2.30 on 2026-06-04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_apollo_rejected_email_audit"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("provider", models.CharField(default="emailverifier.io", max_length=50)),
                ("decision", models.CharField(choices=[("allow", "Allow"), ("block", "Block"), ("defer", "Defer")], db_index=True, max_length=20)),
                ("provider_status", models.CharField(blank=True, db_index=True, default="", max_length=100)),
                ("reason", models.CharField(blank=True, default="", max_length=500)),
                ("is_catch_all", models.BooleanField(db_index=True, default=False)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("verified_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-verified_at", "email"],
            },
        ),
    ]
