# Generated by Django 4.2.30 on 2026-06-04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_emailverification"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCompanyReplyStop",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stop_date", models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ("respondent_email", models.EmailField(blank=True, default="", max_length=254)),
                ("reply_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("reason", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="daily_reply_stops", to="core.company")),
                ("matched_sent_log", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="daily_company_reply_stops", to="core.sentemaillog")),
                ("reply_event", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="daily_company_reply_stops", to="core.inboxscanevent")),
            ],
            options={
                "ordering": ["-stop_date", "company__normalized_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="dailycompanyreplystop",
            constraint=models.UniqueConstraint(fields=("company", "stop_date"), name="uniq_daily_company_reply_stop"),
        ),
    ]
