# Generated by Django 4.2.30 on 2026-06-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_dailycompanyreplystop'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycompanyreplystop',
            name='decision_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dailycompanyreplystop',
            name='decision_source',
            field=models.CharField(choices=[('rule', 'Rule'), ('openai', 'OpenAI'), ('manual', 'Manual')], db_index=True, default='rule', max_length=20),
        ),
        migrations.AddField(
            model_name='dailycompanyreplystop',
            name='manual_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dailycompanyreplystop',
            name='reply_decision',
            field=models.CharField(choices=[('stop', 'Stop'), ('continue', 'Continue'), ('review', 'Needs Review')], db_index=True, default='stop', max_length=20),
        ),
        migrations.AddField(
            model_name='dailycompanyreplystop',
            name='reply_excerpt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
